Itens should be returned in list
herbsjs/todolist-on-herbs pull request #147
Opened 2022-07-28 13:44 UTC by vitorgamer58

Fixes #
Solved https://github.com/herbsjs/todolist-on-herbs/issues/124
Items were not being returned in the list.

## Proposed Changes

1. Added a for to loop through the list array and fetch matching items.

## Readiness Checklist

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request
- [x] Remember to check if code coverage decrease, if so, please implement the necessary tests

### Reviewing Maintainer
- [x] Label as `breaking` if this is a large fundamental change
- [x] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

2022-07-28 13:54 UTC, vitorgamer58 commented
Working fine
![Screenshot_6952](https://user-images.githubusercontent.com/8906065/181520971-cb733b1b-9786-4943-b0ba-955888183173.png)
![Screenshot_6953](https://user-images.githubusercontent.com/8906065/181522584-c782890e-37d8-47fd-85a0-1a4c181af727.png)

2022-08-02 00:36 UTC, italojs requested changes

2022-08-02 00:36 UTC, italojs commented on src/domain/usecases/getLists.js
> +        for (let index = 0; index < lists.length; index++) {
why not put the listID inside the item?
The big(O) for this function looks complex, we have a loop inside a loop of lists

2022-08-02 00:45 UTC, vitorgamer58 commented on src/domain/usecases/getLists.js
> +        for (let index = 0; index < lists.length; index++) {
I don't think it's necessary to put the listId in the Item, because the items are children of the list object, which has the attributes "id", "name" and "items".
But it is possible to do, just go through the list of items with another loop.

2022-09-05 00:59 UTC, merged