Implementation of Style and Behaviors into the Herbs Shelf
herbsjs/todolist-on-herbs pull request #39
Opened 2020-10-18 01:45 UTC by endersoncosta

I've implements some style and behaviors into the Herbs Shelf...

You can see here:

![gif](https://s8.gifyu.com/images/gifHerbs.gif)

2020-10-19 13:16 UTC, dalssoft commented
Great improvement! Tks!

In order to improve maintainability, could you break the html/css string into functions or files? Tks

2020-10-19 13:30 UTC, jhomarolo requested changes
Thanks for the PR, I made just a few considerations to keep the code more independent and readable.

2020-10-19 13:30 UTC, jhomarolo commented on backend/src/infra/herbsshelf/shelf.js
> +      /* color definition */
Would it be possible to remove this inline css  and put it in another file?

2020-10-20 21:02 UTC, endersoncosta commented
Thanks!! I will work soon as possible...

2020-10-25 12:19 UTC, endersoncosta commented on backend/src/infra/herbsshelf/shelf.js
> +      @import url("https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&display=swap");
We can't remove all external dependency, because that we can't insert (in this case) a font into html...

In other projects, they use a "exclusive" CDN to import the dependencies

Example: [Graphql Playground](https://github.com/graphql/graphql-playground/blob/master/packages/graphql-playground-html/src/render-playground-page.ts)

2020-10-25 12:57 UTC, endersoncosta commented on backend/src/infra/herbsshelf/shelf.js
> +      /* color definition */
Yes, I will made this change now

2020-10-27 12:20 UTC, merged