Add herbs2rest
herbsjs/todolist-on-herbs pull request #54
Opened 2021-05-13 02:29 UTC by gabrielmellooliveira

## Add herbs2rest

1. New express routes generated by herbs2rest.
2. New function to delete a list. 
3. Front-end consume rest API.

2021-05-14 17:01 UTC, jhomarolo commented
@gabrielmellooliveira this PR is ready to be analyzed?

2021-05-14 17:19 UTC, jhomarolo commented
@gabrielmellooliveira this PR is broken, some lint error, could you please check this?

2021-05-15 01:00 UTC, gabrielmellooliveira commented
@jhomarolo I committed the changes to improve the use of herbs2rest and correct lint error

2021-05-15 11:52 UTC, dalssoft requested changes

2021-05-15 11:52 UTC, dalssoft commented on backend/src/domain/usecases/_uclist.js
> +        { usecase: require('./getList').getList(injection), tags: { group: 'List' } },
It should be removed, right?

2021-05-15 11:52 UTC, dalssoft commented on backend/src/infra/api/rest/controllerList.js
> +    getAll: require('../../../domain/usecases/getLists').getLists,
Where is the example for GetByID?

2021-05-15 11:52 UTC, dalssoft commented on frontend/src/pages/Home/Home.js
> +          This is a sample Todo List graphQL/rest API using Herbs using Buchu, Gotu,
This text could be improved:
`This is a To Do List application with the purpose of demonstrate the use of Herbs and some important glues (GraphQL, REST, repository, etc)`

2021-05-15 22:14 UTC, gabrielmellooliveira commented on frontend/src/pages/Home/Home.js
> +          This is a sample Todo List graphQL/rest API using Herbs using Buchu, Gotu,
Yes, I updated the text

2021-05-15 22:15 UTC, gabrielmellooliveira commented on backend/src/domain/usecases/_uclist.js
> +        { usecase: require('./getList').getList(injection), tags: { group: 'List' } },
Right, removed

2021-05-15 22:17 UTC, gabrielmellooliveira commented on backend/src/infra/api/rest/controllerList.js
> +    getAll: require('../../../domain/usecases/getLists').getLists,
I added, but as the focus of GetById is on the params field, so this is not the best example yet

2021-05-22 16:43 UTC, dalssoft approved these changes

2021-05-22 16:55 UTC, merged