Get item- Implementation Back End
herbsjs/todolist-on-herbs pull request #61
Opened 2021-07-08 22:33 UTC by nathalia45

## Proposed Changes

1. Implements get Item usecase on the backend.
2. Implements unit test for get item usecase.

2021-07-09 14:04 UTC, dalssoft requested changes
Try to remove files from this PR if the only modification is tabs and spaces and small syntax changes.

2021-07-09 14:04 UTC, dalssoft commented on backend/src/domain/usecases/getItems.js
> +            'If it is was informed one ID': step(async(ctx) => {
The current state of the code and the description of this use case seems to run with one id or no id. 
But since `ids` from request is a array this use case should return multiple items (or just one if the array has just one item) or all items (if not informed any id).

2021-07-16 23:11 UTC, juliadibo commented on backend/src/domain/usecases/deleteItem.js
> +            const item = ctx.item = ret[0]
You don´t need this line, the `ret` is already the item you are looking for.

2021-07-16 23:24 UTC, juliadibo commented on backend/src/domain/usecases/getItems.js
> +                console.log("dj gilmar")
Please, remove console.log

2021-07-16 23:26 UTC, juliadibo commented on backend/src/infra/api/graphql/queries.js
> +    require('../../../domain/usecases/getItems').getItems
switch these lines, leaving `/* Add more use cases here */` at the end os the array.

2021-07-22 21:58 UTC, jhomarolo requested changes

2021-07-22 21:58 UTC, jhomarolo commented on backend/src/domain/usecases/deleteItem.test.js
> +        const ret = await uc.run({ id: req.id })
Hi @nathalia45 this test is broken.

Please see the run report: https://github.com/herbsjs/todolist-on-herbs/pull/61/checks?check_run_id=3138583398

2021-07-22 22:30 UTC, nathalia45 commented on backend/src/domain/usecases/deleteItem.test.js
> +        const ret = await uc.run({ id: req.id })
They were fixed @jhomarolo

2021-07-22 22:58 UTC, jhomarolo commented
@nathalia45 the lint is now breaking: https://github.com/herbsjs/todolist-on-herbs/pull/61/checks?check_run_id=3138830888

2021-07-23 18:07 UTC, nathalia45 commented
> @nathalia45 the lint is now breaking: https://github.com/herbsjs/todolist-on-herbs/pull/61/checks?check_run_id=3138830888

Fixed

2021-07-24 21:12 UTC, jhomarolo commented
Thank you @nathalia45 for the fixes. @juliadibo, what you asked to be changed is correct now?

2021-07-28 01:06 UTC, merged